name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true
      - run: deno task build
      # NOTE: This step will fail until the sample code is replaced.
      #       It is expected that this step fails in the template.
      #       Once it is replaced, please delete this comment.
      - run: deno task check
